### ISSUE TITLE
Pack is not launching after last update 

### ISSUE THREAD

**Issue by xiCrystalx** [The-Nexus-Project/Limitless-Lite#13]
Game is not starting after ''TNP Limitless 7'' loading screen. Game is freezing on black screen and the only thing i can do is close it from windows task manager. Is there any solution for this?

**Comment by Gbergz** [comment]
Send latest.log

But I am also just gonna guess it's a faulty install or not enough ram allocated.

Reinstall the modpack.

**Comment by xiCrystalx** [comment]
[latest.log](https://github.com/The-Nexus-Project/Limitless-Lite/files/15201321/latest.log)

**Comment by xiCrystalx** [comment]
i have 19gb ram allocated :(

**Comment by Gbergz** [comment]
Lower it to 12 or 14

**Comment by Gbergz** [comment]
Also reinstall the modpack. See if anything changes.

**Comment by Gbergz** [comment]
If you're using Oculus you need to update it
https://legacy.curseforge.com/minecraft/mc-mods/oculus/files/5299671

**Comment by xiCrystalx** [comment]
allocating less ram and reinstalling pack helped. Thanks :)

**Comment by Gbergz** [comment]
Awesome. No problems.
