### ISSUE TITLE
Fix some server lags

### ISSUE THREAD

**Issue by catMaf** [The-Nexus-Project/Limitless-Lite#3]
Sometimes the server starts to lag.
Is there any command like **_/worldborder fill_** on the server?

**Comment by choekstr** [comment]
so far only thing I have found to fix that is to restart the server.  Hoping others might have a trick to fix it, but I can't even determine what it is right now as nothing in particular is lagging, just overall slow and low tps

**Comment by Gbergz** [comment]
Lag? What type of lag? Stutters?
How much ram? PC specs? Seems weird to that it would lag.

**Comment by choekstr** [comment]
no one is on, nothing happening, just all of a sudden this happens.  Or when we go to the end, and come back or stay in the end.  Happened when one user went to the bumblezone as well.  Just will tank for no apparent reason.  This is now happening on my server with TPS at 10ms.

In general if we have the server running for say 48 hours it invariably tends to happen.  If we reboot it once a night it doesn't happen.  I have checked there are no overflowing mob farms or weird buildup of mobs that I can see.

This is my server setup, not sure about @catMaf :
128G ram with 10Gb allocated to pack
AMD 5950x with 32 cores
NVME 4.0 2TB 970 Pro

> [10:33:47] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 14392ms or 287 ticks behind
[10:34:16] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 13924ms or 278 ticks behind
[10:34:44] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 12792ms or 255 ticks behind
[10:35:11] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 12572ms or 251 ticks behind
[10:35:39] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 12651ms or 253 ticks behind
[10:36:06] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 12305ms or 246 ticks behind
[10:36:34] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 12676ms or 253 ticks behind

**Comment by Gbergz** [comment]
Just making sure you know this is Limitless Lite?

**Comment by choekstr** [comment]
argh.  no, didn't.   Lemme remove my posts.  sorry

**Comment by catMaf** [comment]
> Lag? What type of lag? Stutters?
> How much ram? PC specs? Seems weird to that it would lag.

8gb ram i3 4130 win server 2016
on this pc only minecraft server
sometimes Stutters
3 peoples playing

**Comment by Gbergz** [comment]
Hm. That does seem like a weak pc even for hosting this pack. And is probably why you're struggling. Is that how much ram is allocated or is that the total amount in the pc?

**Comment by catMaf** [comment]
> Hm. That does seem like a weak pc even for hosting this pack. And is probably why you're struggling. Is that how much ram is allocated or is that the total amount in the pc?

allocated 6, but loaded no more than 3

**Comment by Gbergz** [comment]
Yeah probably the cpu then cant handle 3 ppl exploring etc.

**Comment by catMaf** [comment]
cpu loaded on 30-35% xD
stupid java, i think

**Comment by catMaf** [comment]
so thank for answers!

**Comment by Gbergz** [comment]
Could be something else ofcourse, but I have no idea why it would lag if so.
And np.
