### ISSUE TITLE
Not enough andisite

### ISSUE THREAD

**Issue by 64thParaDux** [The-Nexus-Project/Limitless-Lite#4]
Multiple reports on the official server of basically to no andesite generation in the world. same with other vanilla stone variants.

**Comment by Gbergz** [comment]
Quark changes the generation of this. There's recipes for these stones aswell.

**Comment by 64thParaDux** [comment]
I made a solution. Quark has configurable rock deposits and andesite was only in forests so no wonder we are all crying. I made it for all that made sense and that's really it.
https://pastebin.com/nMD8LeWe
