### ISSUE TITLE
Mod Suggestions for TNP Limitless Lite

### ISSUE THREAD

**Issue by Gbergz** [The-Nexus-Project/Limitless-Lite#6]
Closed.

**Comment by mrdeadlocked** [comment]
Balanced Enchanting-
This mod makes it so that enchantments and anvil operations at any level costs the same fixed amount of points.

This is great because 30 levels at 200 xp level is a lot different amount of exp compared to 30 levels at level 30.

https://www.curseforge.com/minecraft/mc-mods/balanced-enchanting

**Comment by Daxamar** [comment]
https://www.curseforge.com/minecraft/mc-mods/redstone-gauges-and-switches

Great Mod. Hope you can ad it.

**Comment by periwinkle93084** [comment]
I know there is the crayfish furniture mod but macaw has one and it adds a lot of variety for chairs, tables, closets, etc.

**Comment by CalebMcElderry** [comment]
https://www.curseforge.com/minecraft/mc-mods/lazierae2

Since ae2 inscribers and etc are annoying to automate on their own.

**Comment by Gbergz** [comment]
@CalebMcElderry think you posted that on the wrong github page, 
https://github.com/The-Nexus-Project/Limitless-3/issues/3

**Comment by Tekkitmaster27** [comment]
Advent of Ascension for a more mmo like experience?
Plus lots more areas to explore! https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine

**Comment by MKALJANABY** [comment]
https://www.curseforge.com/minecraft/mc-mods/solargeneration solar panel!
https://www.curseforge.com/minecraft/mc-mods/orelibrary requirement for solar generation
https://www.curseforge.com/minecraft/mc-mods/planttech-2/files this mod seems pretty large and i don't think you have experience with it before so maybe test it a bit?
https://www.curseforge.com/minecraft/mc-mods/plant-in-a-jar this would fit with the easyvillagers and easypiglins but it might be too easy...? 
https://www.curseforge.com/minecraft/mc-mods/portable-mobs this one i just found interesting but i feel it's a bit op and can't find the uses for it so you decide
sorry if any of them are fabric and i didn't notice

**Comment by Gbergz** [comment]
@MKALJANABY Pretty sure you requested this on the wrong pack suggestion page.

**Comment by MKALJANABY** [comment]
@Gbergz oh i meant this for tnp 6 my bad
