### ISSUE TITLE
Create Crushed Lead Not washing into nuggets

### ISSUE THREAD

**Issue by Meek97** [The-Nexus-Project/Limitless-Lite#7]
The crushed lead ore from the Create mod does not wash into nuggets.

I'm guessing that it's the same thing that was happening in the TNP 3 pack, 
https://github.com/The-Nexus-Project/Limitless-3/issues/130

**Comment by Gbergz** [comment]
Yep, It'll be fixed next update

**Comment by Meek97** [comment]
nice 👍

**Comment by Gbergz** [comment]
Fixed in 2.0.5
https://www.curseforge.com/minecraft/modpacks/tnp-limitless-lite/files/3221650
